import firestore from '@react-native-firebase/firestore';

class Service{

    constructor(collectionName){
        this.collection = collectionName
    }

    getSingleData = async (documentId) => {
        return firestore().collection(this.collection).doc(documentId).get()
            .then(function (response) {
                return { data: response, error: false };
            })
            .catch(function (error) {
                return { data: error, error: true }
            })
    }

    getAllDataOfCollection = async (documentId) => {
        return firestore().collection(this.collection).get()
            .then(function (response) {
                return { data: response, error: false };
            })
            .catch(function (error) {
                return { data: error, error: true }
            })
    }

    deleteData = async (documentId) => {
        return firestore().collection(this.collection).doc(documentId).delete()
            .then(function (response) {
                return { data: 'Data deleted',error: false };
            })
            .catch(function (error) {
                return { data: error, error: true }
            })
    }
    updateData = async (documentId,data) => {
        return firestore().collection(this.collection).doc(documentId).update(data)  
        .then((res) => {
                console.log(res,'Fes');
                return { data: res, error: false }
            })
            .catch((e) => {
                return { data: e, error: true }
            })
    }
    
    createNewDataWithAutogeneratedId = async (data) => {
        return firestore().collection(this.collection).add(data)  
        .then((res) => {
                return { data: res, error: false }
            })
            .catch((e) => {
                return { data: e, error: true }
            })
    }
    
    createNewDataWithoutAutogeneratedId = async (documentId,data) => {
        return firestore().collection(this.collection).doc(documentId).set(data)  
        .then((res) => {
                console.log(res,'Fes');
                return { data: res, error: false }
            })
            .catch((e) => {
                return { data: e, error: true }
            })
    }

}

export default Service